baseURL = "https://k8s-contributors.netlify.com/"
languageCode = "en-us"
title = "Kubernetes Contributors"
disableKinds = ["taxonomy", "taxonomyTerm"]
pygmentsCodefences = true
pygmentsStyle = "dracula"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xHTML = false

[params]
fontAwesomeVersion = "5.8.1"
sansSerifFont = "Roboto"
twitterHandle = "kubernetes"
googleAnalyticsId = "180100527"

[params.fullcalendar]
js = ["core", "google-calendar", "daygrid", "moment"]
css = ["core", "daygrid"]

[[params.fonts]]
name = "Roboto"
sizes = [300,400,600,700]

[menu]

[[menu.sidebar]]
name = "Role Board"
url = "https://discuss.kubernetes.io/c/contributors/role-board"
weight = 99
