baseURL = "https://contributor.kubernetes.io"
DefaultContentLanguage = "en"
title = "Kubernetes Contributor Community"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
publishDir="build/public"

[blackfriday]
extensions = [ "noEmptyLineBeforeBlock"]

[params]
editURL = ""
showVisitedLinks = false # default is false
ordersectionsby = "title" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableNavChevron = true # set true to hide next/prev chevron, default is false
menushortcutsnewtab = false # set true to open shortcuts links to a new tab/window
enableGitInfo = false
sectionPagesMenu="menu"
custom_css = [ "css/overrides.css" ]

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "Glossary"
url = "https://kubernetes.io/docs/reference/glossary/?community=true"
