baseURL: https://contributor.kubernetes.io
DefaultContentLanguage: en
title: Kubernetes Contributor Community
pygmentsCodeFences: true
pygmentsStyle: monokailight
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: false
publishDir: build/public
pluralizeListTitles: false

blackfriday:
  extensions: [ "noEmptyLineBeforeBlock" ]

params:
  sectionPagesMenu: menu

outputs:
  home: [ "HTML", "RSS", "JSON"]

menu:
  shortcuts:
  - name: Calendar
    url: https://contributor.kubernetes.io/calendar?community=true
  - name: Glossary
    url: https://kubernetes.io/docs/reference/glossary/?community=true
